//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESMEOAlertSentLog
    {
        public int ID { get; set; }
        public int WONumber { get; set; }
        public string Asset { get; set; }
        public string MEOClassification { get; set; }
        public Nullable<System.DateTime> MEODue { get; set; }
        public string Shop { get; set; }
        public string AlertTo { get; set; }
        public string AlertCC { get; set; }
        public Nullable<System.DateTime> Alerted { get; set; }
    }
}
