//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvBuilding
    {
        public int ID { get; set; }
        public string Building { get; set; }
        public string Property { get; set; }
        public string BuildingComplex { get; set; }
        public string BuildingCode { get; set; }
        public string BuildingFacility_ { get; set; }
        public string BuildingDescription { get; set; }
        public int Active { get; set; }
    }
}
