//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEDIC
    {
        public int ID { get; set; }
        public string IC_Name { get; set; }
        public string IC_Abbreviation { get; set; }
        public string IC_Director { get; set; }
        public Nullable<int> Active { get; set; }
        public string Description { get; set; }
    }
}
