//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssetEquipment()
        {
            this.tblAssetEquipmentContacts = new HashSet<tblAssetEquipmentContact>();
            this.tblAssetEquipmentDocuments = new HashSet<tblAssetEquipmentDocument>();
            this.tblAssetEquipmentParts = new HashSet<tblAssetEquipmentPart>();
            this.tblAssetEquipmentSpecs = new HashSet<tblAssetEquipmentSpec>();
        }
    
        public string Asset { get; set; }
        public string Property { get; set; }
        public int AssetID { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string GroupName { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public string Account { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string ModelNumber { get; set; }
        public int Warranty { get; set; }
        public Nullable<System.DateTime> DateWarrantyExpire { get; set; }
        public Nullable<System.DateTime> DateInstall { get; set; }
        public Nullable<System.DateTime> DateDisposal { get; set; }
        public string SerialNumber { get; set; }
        public string LicenseNumber { get; set; }
        public float MeterOrMileage { get; set; }
        public Nullable<System.DateTime> MeterLastUpdated { get; set; }
        public Nullable<System.DateTime> MeterLastScheduled { get; set; }
        public Nullable<float> MeterLast { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<System.DateTime> DateReplace { get; set; }
        public decimal CostInstall { get; set; }
        public decimal CostReplacement { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> DateMoveIn { get; set; }
        public Nullable<System.DateTime> DateMoveOut { get; set; }
        public Nullable<System.DateTime> DateLeaseExpire { get; set; }
        public string NameLastOrCompany { get; set; }
        public string NameFirst { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string Parent { get; set; }
        public string Comments { get; set; }
        public float SquareFeet { get; set; }
        public string TenantPrevious { get; set; }
        public Nullable<System.DateTime> DateLastMaintained { get; set; }
        public int ReserveForReplacement { get; set; }
        public int CommentToWO { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ControlNumber { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> Altitude { get; set; }
        public string Family { get; set; }
        public Nullable<int> EquipmentFunction { get; set; }
        public Nullable<int> Risk { get; set; }
        public Nullable<int> MaintenanceClass { get; set; }
        public Nullable<int> AAALAC { get; set; }
        public string Shop { get; set; }
        public string System { get; set; }
        public Nullable<int> BSL { get; set; }
        public string BSLClassification { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        public virtual tblProperty tblProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentContact> tblAssetEquipmentContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentDocument> tblAssetEquipmentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentPart> tblAssetEquipmentParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentSpec> tblAssetEquipmentSpecs { get; set; }
    }
}
