//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetEquipmentPart
    {
        public int ID { get; set; }
        public string Part { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblAssetEquipment tblAssetEquipment { get; set; }
        public virtual tblPart tblPart { get; set; }
    }
}
