//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetActivity
    {
        public int ID { get; set; }
        public string Activity { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<System.DateTime> DateLastDone { get; set; }
        public Nullable<float> TimesPerYear { get; set; }
        public int Track { get; set; }
        public Nullable<decimal> CostEstimated { get; set; }
        public Nullable<float> TimeEstimated { get; set; }
        public string Category { get; set; }
        public string Account { get; set; }
        public int Completed { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
    }
}
