//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetContact
    {
        public int ID { get; set; }
        public string Contact { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string LaborType { get; set; }
        public string ContactSort { get; set; }
        public Nullable<System.DateTime> ContractExpirationDate { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
    }
}
