//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetSystem
    {
        public int ID { get; set; }
        public string SystemTitle { get; set; }
        public string SystemType { get; set; }
        public string SystemGroup { get; set; }
        public string SystemAbbreviation { get; set; }
        public string Description { get; set; }
        public string Property { get; set; }
        public int IsParent { get; set; }
    }
}
