//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetMove
    {
        public int ID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<System.DateTime> MoveDate { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string OldProperty { get; set; }
        public string NewProperty { get; set; }
        public string OldBuilding { get; set; }
        public string NewBuilding { get; set; }
        public string OldFloor { get; set; }
        public string NewFloor { get; set; }
        public string OldParent { get; set; }
        public string NewParent { get; set; }
        public string OldFamily { get; set; }
        public string NewFamily { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
