//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillingHistory
    {
        public int ID { get; set; }
        public string BilledTo { get; set; }
        public Nullable<decimal> Billed { get; set; }
        public string WorkOrder { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
