//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstruction
    {
        public string WO { get; set; }
        public int WOnumber { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Supervisor { get; set; }
        public string RequestedBy { get; set; }
        public string TakenBy { get; set; }
        public string Phone { get; set; }
        public string Task { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<short> Priority { get; set; }
        public string AssetLocation { get; set; }
        public string Project { get; set; }
        public Nullable<float> EstimatedTime { get; set; }
        public Nullable<float> ActualTime { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Requested { get; set; }
        public Nullable<System.DateTime> Issued { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public Nullable<System.DateTime> OnHold { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RemoteSender { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<int> Safety { get; set; }
        public string Shop { get; set; }
        public Nullable<int> Inspection { get; set; }
        public string AccountCharge { get; set; }
        public string Failure { get; set; }
        public Nullable<int> LockoutTagout { get; set; }
        public string WOreport { get; set; }
        public string InspectionReport { get; set; }
        public Nullable<decimal> CostPartActual { get; set; }
        public Nullable<decimal> CostMiscActual { get; set; }
        public Nullable<decimal> CostLaborActual { get; set; }
        public Nullable<decimal> CostlaborStaffActual { get; set; }
        public Nullable<decimal> CostLaborContractorActual { get; set; }
        public Nullable<decimal> CostTotalActual { get; set; }
        public Nullable<decimal> CostTotalEstimated { get; set; }
        public Nullable<decimal> CostPartEstimated { get; set; }
        public Nullable<decimal> CostMiscEstimated { get; set; }
        public Nullable<decimal> CostLaborestimated { get; set; }
        public Nullable<decimal> CostlaborStaffEstimated { get; set; }
        public Nullable<decimal> CostlaborContractorEstimated { get; set; }
        public Nullable<decimal> Chargelabor { get; set; }
        public Nullable<decimal> ChargeStaff { get; set; }
        public Nullable<decimal> ChargeContractor { get; set; }
        public Nullable<decimal> ChargePart { get; set; }
        public Nullable<decimal> ChargeMiscCost { get; set; }
        public Nullable<decimal> ChargeTotal { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string Personnel { get; set; }
        public string Room { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public Nullable<int> JCAHO { get; set; }
        public Nullable<int> AAALAC { get; set; }
        public Nullable<int> ysnComplete { get; set; }
        public string Substatus { get; set; }
        public string RequesterBuilding { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<int> ysnWR { get; set; }
        public Nullable<int> ysnExternal { get; set; }
        public Nullable<int> ysnMSWEB { get; set; }
        public Nullable<int> BSL { get; set; }
        public string NBSNumber { get; set; }
        public string CANNumber { get; set; }
        public Nullable<int> ysnReimbursable { get; set; }
        public Nullable<int> LifeSafety { get; set; }
        public string ConstructionNo { get; set; }
        public string ned_ic_abbreviation { get; set; }
        public string Email { get; set; }
        public string ContractingOfficer { get; set; }
        public string ApprovalOfficer { get; set; }
        public string RequestInitiator { get; set; }
    }
}
