//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstructionEvent
    {
        public int ID { get; set; }
        public string Event { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string UserName { get; set; }
        public string WO { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public string Part { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string Location { get; set; }
        public string LocationOld { get; set; }
        public Nullable<decimal> CostAverage { get; set; }
        public Nullable<decimal> CostAverageOld { get; set; }
        public string Status { get; set; }
        public string PO { get; set; }
        public string Invoice { get; set; }
        public string Supplier { get; set; }
        public string Shop { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ShopFrom { get; set; }
    }
}
