//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerSurvey
    {
        public string WO { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public string Comments { get; set; }
        public Nullable<short> Question1 { get; set; }
        public Nullable<short> Question2 { get; set; }
        public Nullable<short> Question3 { get; set; }
        public Nullable<short> Question4 { get; set; }
        public Nullable<short> Question5 { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
