//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocument()
        {
            this.tblAssetDocuments = new HashSet<tblAssetDocument>();
            this.tblAssetEquipmentDocuments = new HashSet<tblAssetEquipmentDocument>();
            this.tblPartDocuments = new HashSet<tblPartDocument>();
            this.tblTaskDocuments = new HashSet<tblTaskDocument>();
            this.tblWOdocuments = new HashSet<tblWOdocument>();
        }
    
        public string Document { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public byte[] ObjectBinary { get; set; }
        public string FileName { get; set; }
        public int PrintOnWO { get; set; }
        public int Embed { get; set; }
        public string URL { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetDocument> tblAssetDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentDocument> tblAssetEquipmentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartDocument> tblPartDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskDocument> tblTaskDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOdocument> tblWOdocuments { get; set; }
    }
}
