//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDay
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Title { get; set; }
        public Nullable<int> Day_Title { get; set; }
        public string Week { get; set; }
        public Nullable<int> Year_Title { get; set; }
        public Nullable<int> Month_Title { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> DayofYear { get; set; }
        public Nullable<int> WeekofYear { get; set; }
        public Nullable<int> FY { get; set; }
        public Nullable<int> FYMonth { get; set; }
        public Nullable<int> FYQuarter { get; set; }
        public Nullable<int> FYWeek { get; set; }
        public Nullable<int> ysnBusinessDay { get; set; }
    }
}
