//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventSystem
    {
        public int ID { get; set; }
        public string SystemOwnerName { get; set; }
        public string ChangedUserName { get; set; }
        public string ChangedEvent { get; set; }
        public string PreviousUserStatus { get; set; }
        public string NewUserStatus { get; set; }
        public string PreviousUserRole { get; set; }
        public string NewUserRole { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public string Comments { get; set; }
    }
}
