//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm
    {
        public int ID { get; set; }
        public string FormTitle { get; set; }
        public string FormDescription { get; set; }
        public string FormType { get; set; }
        public string FormLocation { get; set; }
        public string FormFileName { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
