//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaborProperty
    {
        public int ID { get; set; }
        public string Property { get; set; }
        public string Labor { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblLabor tblLabor { get; set; }
        public virtual tblProperty tblProperty { get; set; }
    }
}
