//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLabor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLabor()
        {
            this.tblLaborProperties = new HashSet<tblLaborProperty>();
            this.tblLaborTrainings = new HashSet<tblLaborTraining>();
            this.tblTaskLabors = new HashSet<tblTaskLabor>();
            this.tblWOhoursLosts = new HashSet<tblWOhoursLost>();
            this.tblWOlabors = new HashSet<tblWOlabor>();
        }
    
        public string Labor { get; set; }
        public string LaborID { get; set; }
        public string OtherName { get; set; }
        public string Type { get; set; }
        public string Contact { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneMobile { get; set; }
        public string Pager { get; set; }
        public string PagerService { get; set; }
        public string PIN { get; set; }
        public int Numeric { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> CostRegular { get; set; }
        public Nullable<decimal> CostOvertime { get; set; }
        public Nullable<decimal> CostDouble { get; set; }
        public Nullable<decimal> CostOther { get; set; }
        public Nullable<float> ChargePercentage { get; set; }
        public Nullable<decimal> ChargeRate { get; set; }
        public int Active { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateHire { get; set; }
        public Nullable<System.DateTime> DateTermination { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Trade { get; set; }
        public string MaintenanceCategory { get; set; }
        public string Account { get; set; }
        public string CustomerID { get; set; }
        public byte[] Photo { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] Timestamp { get; set; }
        public string CMMSPWD { get; set; }
        public Nullable<System.DateTime> PWDLastUpdated { get; set; }
        public string CMMSPWD01 { get; set; }
        public string CMMSPWD02 { get; set; }
        public string NIHDomain { get; set; }
        public string NIHLogin { get; set; }
        public string NIHRole { get; set; }
        public Nullable<int> ysnBethesda { get; set; }
        public Nullable<int> ysnPoolesville { get; set; }
        public Nullable<int> ysnNorthCarolina { get; set; }
        public Nullable<int> ysnRML { get; set; }
        public Nullable<int> ysnBaltimore { get; set; }
        public Nullable<int> ysnLeased { get; set; }
        public Nullable<int> ysnFrederick { get; set; }
        public Nullable<short> RefreshInterval { get; set; }
        public Nullable<short> DaysLimit { get; set; }
        public Nullable<int> ysnAudioWarning { get; set; }
        public Nullable<int> ysnInventory { get; set; }
        public Nullable<int> ysnConstruction { get; set; }
        public string ConstructionRole { get; set; }
        public Nullable<int> ysnSystemOwner { get; set; }
        public Nullable<int> LoginFailCount { get; set; }
        public Nullable<System.DateTime> LoginFailLast { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLaborProperty> tblLaborProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLaborTraining> tblLaborTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskLabor> tblTaskLabors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOhoursLost> tblWOhoursLosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOlabor> tblWOlabors { get; set; }
    }
}
