//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaborWorkDay
    {
        public int ID { get; set; }
        public Nullable<int> Work { get; set; }
        public string WorkDay { get; set; }
        public Nullable<short> Tag { get; set; }
    }
}
