//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMiscCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMiscCost()
        {
            this.tblTaskMiscCosts = new HashSet<tblTaskMiscCost>();
            this.tblWOmiscCosts = new HashSet<tblWOmiscCost>();
        }
    
        public string MiscCost { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<float> ChargePercentage { get; set; }
        public Nullable<decimal> ChargePrice { get; set; }
        public string MaintenanceCategory { get; set; }
        public string Account { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskMiscCost> tblTaskMiscCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOmiscCost> tblWOmiscCosts { get; set; }
    }
}
