//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMEOClassification
    {
        public int ID { get; set; }
        public string MEOClassification { get; set; }
        public string Description { get; set; }
        public Nullable<short> PWSPriorityCode { get; set; }
        public string ClassificationLevel { get; set; }
        public string MaintenanceCategory { get; set; }
        public string Shop { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<float> NotificationHours { get; set; }
        public Nullable<float> Onsiteworkinghours { get; set; }
        public Nullable<float> Onsitenonworkinghours { get; set; }
        public Nullable<float> Duehours { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
