//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int ID { get; set; }
        public string MessageType { get; set; }
        public string MessageTitle { get; set; }
        public string Message { get; set; }
        public Nullable<int> Active { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> listorder { get; set; }
    }
}
