//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMEOPriority
    {
        public int ID { get; set; }
        public string MEOPriority { get; set; }
        public string Description { get; set; }
        public Nullable<short> MEOPriorityCode { get; set; }
        public Nullable<float> ResponseWorkingHours { get; set; }
        public Nullable<float> ResponseNonWorkingHours { get; set; }
        public Nullable<float> AbatementWorkinghours { get; set; }
        public Nullable<float> AbatementNonWorkinghours { get; set; }
        public Nullable<float> CompleteHours { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<float> PCTProjectCompleteHours { get; set; }
    }
}
