//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Part { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Location { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Received { get; set; }
        public Nullable<int> ToReceive { get; set; }
        public Nullable<int> BackOrdered { get; set; }
        public string Code { get; set; }
        public string Comments { get; set; }
        public int Taxable { get; set; }
        public Nullable<float> Tax { get; set; }
        public string SupplierPartNumber { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
