//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartDocument
    {
        public int ID { get; set; }
        public string Document { get; set; }
        public string Part { get; set; }
        public Nullable<short> Quantity { get; set; }
        public int PrintonWO { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblDocument tblDocument { get; set; }
        public virtual tblPart tblPart { get; set; }
    }
}
