//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProperty()
        {
            this.tblAssets = new HashSet<tblAsset>();
            this.tblAssetEquipments = new HashSet<tblAssetEquipment>();
            this.tblLaborProperties = new HashSet<tblLaborProperty>();
            this.tblPropertySpecs = new HashSet<tblPropertySpec>();
        }
    
        public string Property { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Owner { get; set; }
        public string OwnerContact { get; set; }
        public string OwnerAddress { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerCountry { get; set; }
        public string OwnerZip { get; set; }
        public string OwnerPhone { get; set; }
        public string OwnerFax { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerURL { get; set; }
        public string Police { get; set; }
        public string Security { get; set; }
        public string Fire { get; set; }
        public Nullable<float> SquareFeet { get; set; }
        public string Comments { get; set; }
        public int Active { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<short> MEOBusinessStartHour { get; set; }
        public Nullable<short> MEOBusinessStartMinute { get; set; }
        public Nullable<short> MEOBusinessEndHour { get; set; }
        public Nullable<short> MEOBusinessEndMinute { get; set; }
        public Nullable<short> MEOAlertMinutesAhead { get; set; }
        public Nullable<short> MEOAlertPriorityMinimum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAsset> tblAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipment> tblAssetEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLaborProperty> tblLaborProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPropertySpec> tblPropertySpecs { get; set; }
    }
}
