//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartSupplier
    {
        public int ID { get; set; }
        public string Supplier { get; set; }
        public string Part { get; set; }
        public string SupplierPartNumber { get; set; }
        public Nullable<decimal> SupplierPrice { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<int> DaysToDeliver { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblPart tblPart { get; set; }
    }
}
