//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertySpec
    {
        public int ID { get; set; }
        public string Spec { get; set; }
        public string Property { get; set; }
        public Nullable<float> ValueNumeric { get; set; }
        public string ValueText { get; set; }
        public Nullable<float> ValueHi { get; set; }
        public Nullable<float> ValueLow { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblProperty tblProperty { get; set; }
    }
}
