//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPart()
        {
            this.tblAssetEquipmentParts = new HashSet<tblAssetEquipmentPart>();
            this.tblAssetParts = new HashSet<tblAssetPart>();
            this.tblPartDocuments = new HashSet<tblPartDocument>();
            this.tblPartLocations = new HashSet<tblPartLocation>();
            this.tblPartSpecs = new HashSet<tblPartSpec>();
            this.tblPartSuppliers = new HashSet<tblPartSupplier>();
        }
    
        public string Part { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public string Class { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Supplier { get; set; }
        public string SupplierPartNumber { get; set; }
        public int Stock { get; set; }
        public int Hazardous { get; set; }
        public string Account { get; set; }
        public string ABCCode { get; set; }
        public string ControlNumber { get; set; }
        public string CycleCount { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> CostCase { get; set; }
        public Nullable<int> SizeCase { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<decimal> CostLast { get; set; }
        public Nullable<decimal> OrderLast { get; set; }
        public Nullable<System.DateTime> IssueLast { get; set; }
        public Nullable<System.DateTime> PhysicalLast { get; set; }
        public Nullable<decimal> CostAverage { get; set; }
        public Nullable<decimal> ChargePrice { get; set; }
        public Nullable<float> ChargePercentage { get; set; }
        public string MaintenanceCategory { get; set; }
        public int ReserveForReplacement { get; set; }
        public string Comments { get; set; }
        public string Documentation { get; set; }
        public Nullable<float> ShippingWeight { get; set; }
        public int Active { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] TimeStamp { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetEquipmentPart> tblAssetEquipmentParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetPart> tblAssetParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartDocument> tblPartDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartLocation> tblPartLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartSpec> tblPartSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartSupplier> tblPartSuppliers { get; set; }
    }
}
