//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        public string Site { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public Nullable<short> DataVersionMajor { get; set; }
        public Nullable<short> DataVersionMinor { get; set; }
        public Nullable<int> EventRecords { get; set; }
        public Nullable<float> SalesTaxRate { get; set; }
        public Nullable<System.DateTime> MIMdateFrom { get; set; }
        public Nullable<System.DateTime> MIMdateTo { get; set; }
        public int MIMwoc { get; set; }
        public Nullable<short> TaskAdvanceDays { get; set; }
        public Nullable<System.DateTime> TaskDateLastSchedule { get; set; }
        public Nullable<short> TaskDayToCheck { get; set; }
        public string TableLink { get; set; }
        public int SampleData { get; set; }
        public Nullable<float> SalesTaxRateLabor { get; set; }
        public Nullable<float> SalesTaxRateOtherCost { get; set; }
        public string International { get; set; }
        public int TrackActivity { get; set; }
        public string Platform { get; set; }
        public byte[] TimeStamp { get; set; }
        public string WRLink { get; set; }
        public string WOLink { get; set; }
    }
}
