//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStandard
    {
        public int ID { get; set; }
        public string Standard { get; set; }
        public int Active { get; set; }
        public string Description { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
    }
}
