//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShop
    {
        public string Shop { get; set; }
        public string Description { get; set; }
        public string ShopSupervisor { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SurveyTO { get; set; }
        public string SurveyCC { get; set; }
        public Nullable<int> Active { get; set; }
        public string UDF1 { get; set; }
        public Nullable<int> ysnMobile { get; set; }
        public string Property { get; set; }
        public string AlertTo { get; set; }
        public string AlertCC { get; set; }
    }
}
