//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskSchedule
    {
        public int ID { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> DateSchedule { get; set; }
        public Nullable<float> TimeStandard { get; set; }
        public string Property { get; set; }
        public string Asset { get; set; }
        public Nullable<int> AssetID { get; set; }
        public int MultiLabor { get; set; }
        public Nullable<short> LaborCount { get; set; }
        public Nullable<float> MeterLast { get; set; }
        public string ProjectSchedule { get; set; }
        public string Description { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
