//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTask()
        {
            this.tblTaskActivities = new HashSet<tblTaskActivity>();
            this.tblTaskAssets = new HashSet<tblTaskAsset>();
            this.tblTaskAssetActivities = new HashSet<tblTaskAssetActivity>();
            this.tblTaskAssetInspections = new HashSet<tblTaskAssetInspection>();
            this.tblTaskDocuments = new HashSet<tblTaskDocument>();
            this.tblTaskInspections = new HashSet<tblTaskInspection>();
            this.tblTaskLabors = new HashSet<tblTaskLabor>();
            this.tblTaskMiscCosts = new HashSet<tblTaskMiscCost>();
            this.tblTaskParts = new HashSet<tblTaskPart>();
            this.tblTaskTools = new HashSet<tblTaskTool>();
        }
    
        public string Task { get; set; }
        public string WO { get; set; }
        public string Kind { get; set; }
        public string Shop { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Supervisor { get; set; }
        public string RequestedBy { get; set; }
        public string Phone { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<short> Priority { get; set; }
        public string MaintenanceCategory { get; set; }
        public int Warranty { get; set; }
        public int ShutdownBox { get; set; }
        public int Safety { get; set; }
        public string Project { get; set; }
        public string SpecialInstruction { get; set; }
        public string Frequency { get; set; }
        public Nullable<short> NumberOfDays { get; set; }
        public Nullable<short> DayOfMonth { get; set; }
        public int OnSunday { get; set; }
        public int OnMonday { get; set; }
        public int OnTuesday { get; set; }
        public int OnWednesday { get; set; }
        public int OnThursday { get; set; }
        public int OnFriday { get; set; }
        public int OnSaturday { get; set; }
        public Nullable<short> AnnualMonthStart { get; set; }
        public Nullable<short> AnnualDayStart { get; set; }
        public Nullable<short> AnnualMonthEnd { get; set; }
        public Nullable<short> AnnualDayEnd { get; set; }
        public Nullable<System.DateTime> ScheduledLast { get; set; }
        public Nullable<System.DateTime> ScheduledLastUpdate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<float> TimeStandard { get; set; }
        public Nullable<short> TimesDone { get; set; }
        public Nullable<float> TimeAverage { get; set; }
        public string WOlast { get; set; }
        public Nullable<System.DateTime> DoneLast { get; set; }
        public int Inspection { get; set; }
        public int LockoutTagout { get; set; }
        public string WOreport { get; set; }
        public string InspectionReport { get; set; }
        public string AccountCharge { get; set; }
        public Nullable<decimal> CostTotalEstimated { get; set; }
        public Nullable<decimal> CostPartEstimated { get; set; }
        public Nullable<decimal> CostMiscEstimated { get; set; }
        public Nullable<decimal> CostLaborEstimated { get; set; }
        public Nullable<decimal> CostLaborStaffEstimated { get; set; }
        public Nullable<decimal> CostLaborContractorEstimated { get; set; }
        public string Class { get; set; }
        public Nullable<float> MeterInterval { get; set; }
        public Nullable<float> MeterLast { get; set; }
        public string Training { get; set; }
        public Nullable<int> LastCompleted { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] TimeStamp { get; set; }
        public string RequesterBuilding { get; set; }
        public string Room { get; set; }
        public string ScheduleGroup { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskActivity> tblTaskActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskAsset> tblTaskAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskAssetActivity> tblTaskAssetActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskAssetInspection> tblTaskAssetInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskDocument> tblTaskDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskInspection> tblTaskInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskLabor> tblTaskLabors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskMiscCost> tblTaskMiscCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskPart> tblTaskParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskTool> tblTaskTools { get; set; }
    }
}
