//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskScheduleWO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTaskScheduleWO()
        {
            this.tblTaskScheduleWOactivities = new HashSet<tblTaskScheduleWOactivity>();
            this.tblTaskScheduleWOInspectionPoints = new HashSet<tblTaskScheduleWOInspectionPoint>();
        }
    
        public int ID { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> DateSchedule { get; set; }
        public Nullable<float> TimeStandard { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<int> AssetID { get; set; }
        public int MultiLabor { get; set; }
        public Nullable<short> LaborCount { get; set; }
        public Nullable<float> MeterLast { get; set; }
        public string ProjectSchedule { get; set; }
        public string Description { get; set; }
        public byte[] TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskScheduleWOactivity> tblTaskScheduleWOactivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskScheduleWOInspectionPoint> tblTaskScheduleWOInspectionPoints { get; set; }
    }
}
