//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskMiscCost
    {
        public int ID { get; set; }
        public string Task { get; set; }
        public string MiscCost { get; set; }
        public string MaintenanceCategory { get; set; }
        public string Account { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblMiscCost tblMiscCost { get; set; }
        public virtual tblTask tblTask { get; set; }
    }
}
