//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTool()
        {
            this.tblTaskTools = new HashSet<tblTaskTool>();
            this.tblWOtools = new HashSet<tblWOtool>();
        }
    
        public string Tool { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Comments { get; set; }
        public string Labor { get; set; }
        public string Property { get; set; }
        public byte[] TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskTool> tblTaskTools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOtool> tblWOtools { get; set; }
    }
}
