//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWOAssetComponent
    {
        public int ID { get; set; }
        public string WO { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> Passed { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<int> AssignWO { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Recorded { get; set; }
    
        public virtual tblWO tblWO { get; set; }
    }
}
