//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWOtype
    {
        public string WOtype { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkOrder { get; set; }
        public Nullable<int> Task { get; set; }
        public Nullable<int> MEO { get; set; }
        public Nullable<int> HelpDesk { get; set; }
        public Nullable<int> MSWeb { get; set; }
        public Nullable<int> FullVersion { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
