//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWR
    {
        public int WRnumber { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public string WO { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public string RequestedBy { get; set; }
        public string RequesterPhone { get; set; }
        public string Type { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<System.DateTime> Requested { get; set; }
        public string RemoteSender { get; set; }
        public string RequesterRoom { get; set; }
        public string RequesterBuilding { get; set; }
        public string WorkLocationRoom { get; set; }
        public string WorkLocationBuilding { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string AssetLocation { get; set; }
        public Nullable<short> Priority { get; set; }
        public string Shop { get; set; }
        public Nullable<int> JCAHO { get; set; }
        public Nullable<int> AAALAC { get; set; }
        public string Floor { get; set; }
        public string TakenBy { get; set; }
        public string Personnel { get; set; }
        public string Email { get; set; }
        public string ned_ic_abbreviation { get; set; }
        public string MEOClassification { get; set; }
        public string WRNum { get; set; }
    }
}
