//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWO()
        {
            this.tblWOactivities = new HashSet<tblWOactivity>();
            this.tblWOAssetComponents = new HashSet<tblWOAssetComponent>();
            this.tblWOdocuments = new HashSet<tblWOdocument>();
            this.tblWOhoursLosts = new HashSet<tblWOhoursLost>();
            this.tblWOinspections = new HashSet<tblWOinspection>();
            this.tblWOlabors = new HashSet<tblWOlabor>();
            this.tblWOmiscCosts = new HashSet<tblWOmiscCost>();
            this.tblWOparts = new HashSet<tblWOpart>();
            this.tblWOtools = new HashSet<tblWOtool>();
        }
    
        public string WO { get; set; }
        public int WOnumber { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Supervisor { get; set; }
        public string RequestedBy { get; set; }
        public string TakenBy { get; set; }
        public string Phone { get; set; }
        public string Task { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public short Priority { get; set; }
        public string AssetLocation { get; set; }
        public string Project { get; set; }
        public Nullable<short> ProjectPriority { get; set; }
        public float EstimatedTime { get; set; }
        public Nullable<float> ActualTime { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Requested { get; set; }
        public Nullable<System.DateTime> Issued { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public Nullable<System.DateTime> OnHold { get; set; }
        public System.DateTime Due { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RemoteSender { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<int> ShutdownBox { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<int> PrintAlternateWO { get; set; }
        public Nullable<int> Safety { get; set; }
        public Nullable<int> FromTask { get; set; }
        public string Shop { get; set; }
        public Nullable<int> Printed { get; set; }
        public Nullable<int> Inspection { get; set; }
        public string AccountCharge { get; set; }
        public string Failure { get; set; }
        public Nullable<int> LockoutTagout { get; set; }
        public string Training { get; set; }
        public string WOreport { get; set; }
        public string InspectionReport { get; set; }
        public decimal CostPartActual { get; set; }
        public decimal CostMiscActual { get; set; }
        public decimal CostLaborActual { get; set; }
        public decimal CostlaborStaffActual { get; set; }
        public decimal CostLaborContractorActual { get; set; }
        public decimal CostTotalActual { get; set; }
        public decimal CostTotalEstimated { get; set; }
        public decimal CostPartEstimated { get; set; }
        public decimal CostMiscEstimated { get; set; }
        public decimal CostLaborestimated { get; set; }
        public decimal CostlaborStaffEstimated { get; set; }
        public decimal CostlaborContractorEstimated { get; set; }
        public decimal Chargelabor { get; set; }
        public decimal ChargeStaff { get; set; }
        public decimal ChargeContractor { get; set; }
        public decimal ChargePart { get; set; }
        public decimal ChargeMiscCost { get; set; }
        public decimal ChargeTotal { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<int> Paged { get; set; }
        public string Personnel { get; set; }
        public string Room { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public Nullable<int> JCAHO { get; set; }
        public Nullable<int> AAALAC { get; set; }
        public Nullable<int> ysnComplete { get; set; }
        public Nullable<int> ysnPrint { get; set; }
        public Nullable<int> ysnViewed { get; set; }
        public string Substatus { get; set; }
        public string RequesterBuilding { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<int> ysnWR { get; set; }
        public Nullable<int> ysnExternal { get; set; }
        public Nullable<int> ysnMobile { get; set; }
        public Nullable<int> ysnMSWeb { get; set; }
        public Nullable<int> BSL { get; set; }
        public string MEOClassification { get; set; }
        public Nullable<System.DateTime> MEONotification { get; set; }
        public Nullable<System.DateTime> MEOOnsite { get; set; }
        public Nullable<System.DateTime> MEODue { get; set; }
        public Nullable<int> ysnNotification { get; set; }
        public Nullable<System.DateTime> Notification { get; set; }
        public Nullable<int> ysnOnsite { get; set; }
        public Nullable<System.DateTime> OnSite { get; set; }
        public Nullable<int> ysnAlert { get; set; }
        public Nullable<int> ysnReimbursable { get; set; }
        public string NBSNumber { get; set; }
        public Nullable<int> LifeSafety { get; set; }
        public Nullable<System.DateTime> Abated { get; set; }
        public Nullable<int> ysnAbated { get; set; }
        public Nullable<System.DateTime> MEOAbated { get; set; }
        public Nullable<int> ConfinedSpace { get; set; }
        public string LOTO { get; set; }
        public string SubService { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOactivity> tblWOactivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOAssetComponent> tblWOAssetComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOdocument> tblWOdocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOhoursLost> tblWOhoursLosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOinspection> tblWOinspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOlabor> tblWOlabors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOmiscCost> tblWOmiscCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOpart> tblWOparts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWOtool> tblWOtools { get; set; }
    }
}
