//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWOmiscCost
    {
        public int ID { get; set; }
        public string WO { get; set; }
        public string MiscCost { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostExtendedEstimated { get; set; }
        public Nullable<decimal> CostExtendedActual { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> ChargeExtended { get; set; }
        public Nullable<float> ChargePercentage { get; set; }
        public int ChargeAuto { get; set; }
        public int CostAuto { get; set; }
        public string MaintenanceCategory { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> MiscCostDate { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual tblMiscCost tblMiscCost { get; set; }
        public virtual tblWO tblWO { get; set; }
    }
}
