//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZReportRole
    {
        public int ID { get; set; }
        public string ReportTitle { get; set; }
        public string ReportID { get; set; }
        public string ReportVersion { get; set; }
        public string NIHRole { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
