//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZappuser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string TakenBy { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ShopOption { get; set; }
        public string ShopSupervisorOption { get; set; }
        public string AssetOption { get; set; }
        public string LaborOption { get; set; }
        public Nullable<int> PriorityOption { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> UserLocalDate { get; set; }
        public string AccountCategoryOption { get; set; }
        public string ComputerName { get; set; }
    }
}
