//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZReport
    {
        public int ID { get; set; }
        public string ReportTitle { get; set; }
        public string Description { get; set; }
        public string ReportServer { get; set; }
        public string ReportURL { get; set; }
        public string ReportID { get; set; }
        public string ReportVersion { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string ReportCategory { get; set; }
        public Nullable<short> ReportTabPage { get; set; }
        public Nullable<int> CriDateStart { get; set; }
        public Nullable<int> CriDateEnd { get; set; }
        public Nullable<int> CriShop { get; set; }
        public Nullable<int> CriSupervisor { get; set; }
        public Nullable<int> CriProperty { get; set; }
        public Nullable<int> CriBuilding { get; set; }
        public Nullable<int> CriFacilityNo { get; set; }
        public Nullable<int> CriKeyWord { get; set; }
        public Nullable<int> CriPersonnel { get; set; }
        public Nullable<int> CriProject { get; set; }
        public Nullable<int> CriPriority { get; set; }
        public Nullable<int> CriType { get; set; }
    }
}
