//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMMResponse
    {
        public int ID { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Requested { get; set; }
        public Nullable<System.DateTime> Issued { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> OnHold { get; set; }
        public string Status { get; set; }
        public string Substatus { get; set; }
        public Nullable<float> ActualTime { get; set; }
        public string Personnel { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public Nullable<decimal> CostLaborActual { get; set; }
        public Nullable<decimal> CostPartActual { get; set; }
        public string Description { get; set; }
        public string SpecialInstruction { get; set; }
        public string Shop { get; set; }
        public string Failure { get; set; }
        public Nullable<int> IsSendToTeamm { get; set; }
        public Nullable<int> ExceptionID { get; set; }
        public string Previous_Status { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
    }
}
