//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMMAssetReference
    {
        public int ReferenceID { get; set; }
        public string EIN { get; set; }
        public string AssetSystem { get; set; }
        public string AssetSystemControlNumber { get; set; }
        public string Property { get; set; }
        public string AssetEquipment { get; set; }
        public string AssetEquipmentControlNumber { get; set; }
        public Nullable<int> Active { get; set; }
        public string Building { get; set; }
        public string Shop { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string Location { get; set; }
        public string Supervisor { get; set; }
    }
}
