//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMMEventLog
    {
        public int ID { get; set; }
        public string Event { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string UserName { get; set; }
        public Nullable<int> WOnumber { get; set; }
        public string Status { get; set; }
        public string EIN { get; set; }
        public string Description { get; set; }
        public string Asset { get; set; }
        public string Property { get; set; }
        public Nullable<int> ExceptionID { get; set; }
    }
}
